[pytest]
minversion = 7.0
addopts = -q
testpaths = online-bookstore-qa-aliza-sumi/tests
pythonpath = online-bookstore-qa-aliza-sumi
python_files = test_*.py
python_classes = Test*
python_functions = test_*